Create template from document action added
signnow/SignNow.NET pull request #117
Opened 2021-04-22 13:06 UTC by SashaGolovach

2021-04-22 13:11 UTC, IvanBil commented on SignNow.Net/_Internal/Requests/CreateTemplateFromDocumentRequest.cs
> +    internal class CreateTemplateFromDocumentRequest : IContent
зачем это?

2021-04-22 13:13 UTC, IvanBil commented on SignNow.Net/Service/DocumentService.cs
> +            var requestBody = new CreateTemplateFromDocumentRequest
зачем это если можно такой объект передать как параметр?

2021-04-22 13:19 UTC, IvanBil commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +        public void CreateTemplateFromDocumentSuccessfully()
тесты можно делать асинхронными

2021-04-22 13:24 UTC, IvanBil commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +            Assert.IsNotNull(response.Id);
если мы что-то создали, то надо проверить результат не на нул, а реально получить новый документ и убедиться что он есть

2021-04-22 13:24 UTC, SashaGolovach commented on SignNow.Net/Service/DocumentService.cs
> +            var requestBody = new CreateTemplateFromDocumentRequest
done

2021-04-22 13:24 UTC, SashaGolovach commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +        public void CreateTemplateFromDocumentSuccessfully()
done

2021-04-22 13:24 UTC, IvanBil commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +                SignNowTestContext.Documents.CreateTemplateFromDocumentAsync(TestPdfDocumentId, "test template name").Result;
в сайннау АПИ название темплейта обязательно передавать?

2021-04-22 13:24 UTC, SashaGolovach commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +                SignNowTestContext.Documents.CreateTemplateFromDocumentAsync(TestPdfDocumentId, "test template name").Result;
да

2021-04-22 13:26 UTC, SashaGolovach commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +            Assert.IsNotNull(response.Id);
согласен, но большинство тестов в проекте этого не делают, и для того что бы получить созданный темплейт нужно будет написать еще один метод, потому что такого в документ сервисе нету. Это нужно делать?

2021-04-22 13:52 UTC, AlexNDRmac requested changes

2021-04-22 13:52 UTC, AlexNDRmac commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +            Assert.IsNotNull(response.Id);
Что значит `большинство тестов в проекте этого не делают`? Ты тесты вообще видел? Все респонсы проверяются, `Id` валидируется даже, есть extension для этого!

2021-04-22 13:52 UTC, AlexNDRmac commented on SignNow.Net/SignNow.Net.csproj
> +        <PackageVersion>0.8.0</PackageVersion>
Версия пакета устанавливается в `SignNow.props`

2021-04-22 13:57 UTC, AlexNDRmac commented
Нужно еще добавить Examples для каждой feature. Дописать в Changelog все изменения, обновить Readme с ссылками на примеры из Examples и не уронить Cove coverage.

2021-04-22 14:17 UTC, SashaGolovach commented on SignNow.Net/SignNow.Net.csproj
> +        <PackageVersion>0.8.0</PackageVersion>
done

2021-04-22 14:20 UTC, IvanBil commented on SignNow.Net/Model/Requests/CreateTemplateFromDocumentRequest.cs
> +    public class CreateTemplateFromDocumentRequest : IContent
зачем ты наследуешь IContent? у нас же есть для этого JsonHttpContent

2021-04-22 14:26 UTC, SashaGolovach commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +            Assert.IsNotNull(response.Id);
исправил

2021-04-22 14:29 UTC, SashaGolovach commented on SignNow.Net/_Internal/Requests/CreateTemplateFromDocumentRequest.cs
> +    internal class CreateTemplateFromDocumentRequest : IContent
done

2021-04-22 14:34 UTC, IvanBil commented on SignNow.Net/Model/Requests/CreateTemplateFromDocumentRequest.cs
> +        public string DocumentId { get; set; }
так а где твой любимый конструктор? разве твой сервис норм отработает, если класс создать с дефолтными значениями?

2021-04-22 14:38 UTC, SashaGolovach commented on SignNow.Net/Model/Requests/CreateTemplateFromDocumentRequest.cs
> +        public string DocumentId { get; set; }
добавил

2021-04-23 06:19 UTC, AlexNDRmac commented on SignNow.Net/Model/Requests/CreateTemplateFromDocumentRequest.cs
> +    public class CreateTemplateFromDocumentRequest : IContent
JsonHttpContent - internal. Не нужно предоставлять детали компоновки request на уровне пользовательского интерфейса. Для этого предназначены internal классы requests, которые формируют нужный JsonHttpContent

2021-04-23 07:07 UTC, IvanBil approved these changes

2021-04-26 07:02 UTC, AlexNDRmac requested changes

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net.Examples/ExamplesRunner.cs
> +        [DataRow("Template Name")]
Параметризация не нужна, если используется всего лишь один вариант.

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net.Examples/ExamplesRunner.cs
> +        public async Task CreateTemplateFromDocumentTest(string templateName)
Все примеры с Templates вынести в отдельный `#region Templates Examples` в самый низ файла с примерами.

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net.Examples/ExamplesRunner.cs
> +            var document = await testContext.Documents
Для этого уже есть удобный wrapper:
```csharp
var document = DocumentExamples
                .UploadDocumentWithFieldExtract(PdfWithSignatureField, token).Result;
```

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net.Examples/ExamplesRunner.cs
> +            await testContext.Documents.DeleteDocumentAsync(template.Id);
Для того, чтобы в каждом примере не удалять тестовый документ, есть `disposableDocumentId`, инициализируя эту переменную в тест-методе - соответствующий `documentId` будет удален в `TearDown()`

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net.Examples/ExamplesRunner.cs
> +            Assert.AreEqual(templateName, template.Name);
Еще нужно проверить
```csharp
Assert.IsTrue(template.IsTemplate);
```

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +        [DataRow("test template name")]
Это не нужно для всего лишь одного варианта

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net/Interfaces/IDocumentService.cs
> +        Task<CreateTemplateFromDocumentResponse> CreateTemplateFromDocumentAsync(CreateTemplateFromDocumentRequest request, CancellationToken cancellationToken = default);
`CreateTemplateFromDocumentRequest request` - нарушает уже принятый вид интерфейсов. Интерфейсы минималистичны и просты. Зачем тут обертка типа request? Передай `documentId` и `templateName`

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net/Model/Requests/CreateTemplateFromDocumentRequest.cs
> +    public class CreateTemplateFromDocumentRequest
Это лишнее, реквестами пользователь не должен заниматься вообще! Это ответственность сервиса, сформировать нужный реквест.

2021-04-26 07:02 UTC, AlexNDRmac commented on SignNow.Net/Service/DocumentService.cs
> +        public async Task<CreateTemplateFromDocumentResponse> CreateTemplateFromDocumentAsync(CreateTemplateFromDocumentRequest request, CancellationToken cancellationToken = default)
После изменения интерфейса, посмотри как сделана реализация `MergeDocumentsAsync` и как там формируется request.

2021-04-26 07:26 UTC, SashaGolovach commented on SignNow.Net.Examples/ExamplesRunner.cs
> +        [DataRow("Template Name")]
done

2021-04-26 07:26 UTC, SashaGolovach commented on SignNow.Net.Examples/ExamplesRunner.cs
> +        public async Task CreateTemplateFromDocumentTest(string templateName)
done

2021-04-26 07:26 UTC, SashaGolovach commented on SignNow.Net.Examples/ExamplesRunner.cs
> +            var document = await testContext.Documents
done

2021-04-26 07:27 UTC, alex-holovach commented on SignNow.Net.Examples/ExamplesRunner.cs
> +            await testContext.Documents.DeleteDocumentAsync(template.Id);
нужно удалять несколько документов, по этому один я записываю в disposableDocumentId, а остальные руками удаляю

2021-04-26 07:27 UTC, SashaGolovach commented on SignNow.Net.Examples/ExamplesRunner.cs
> +            Assert.AreEqual(templateName, template.Name);
done

2021-04-26 07:27 UTC, SashaGolovach commented on SignNow.Net.Test/AcceptanceTests/DocumentServiceTest.CreateTemplateFromDocument.cs
> +        [DataRow("test template name")]
done

2021-04-26 07:27 UTC, SashaGolovach commented on SignNow.Net/Interfaces/IDocumentService.cs
> +        Task<CreateTemplateFromDocumentResponse> CreateTemplateFromDocumentAsync(CreateTemplateFromDocumentRequest request, CancellationToken cancellationToken = default);
это было требование @IvanBil передавать обьект, вернул как было раньше

2021-04-26 07:28 UTC, SashaGolovach commented on SignNow.Net/Service/DocumentService.cs
> +        public async Task<CreateTemplateFromDocumentResponse> CreateTemplateFromDocumentAsync(CreateTemplateFromDocumentRequest request, CancellationToken cancellationToken = default)
done

2021-04-26 07:29 UTC, SashaGolovach commented on SignNow.Net/Model/Requests/CreateTemplateFromDocumentRequest.cs
> +    public class CreateTemplateFromDocumentRequest
done

2021-04-26 12:41 UTC, AlexNDRmac approved these changes

2021-04-26 12:41 UTC, merged