MSAPI-59 | Implement Delete Document Action
signnow/SignNow.NET pull request #20
Opened 2019-08-23 19:18 UTC by AlexNDRmac

- fixed platform-specific Path
- implemented Delete Action
- added Acceptance Test
- added Unit Test

2019-08-24 10:21 UTC, IvanBil requested changes

2019-08-24 10:21 UTC, IvanBil commented on SignNow.Net/Service/DocumentService.cs
> +        public async Task<DeleteDocumentResponse> DeleteDocumentAsync(string documentId, CancellationToken cancellationToken = default(CancellationToken))
Какой смысл в DeleteDocumentResponse?

2019-08-24 10:21 UTC, IvanBil commented on SignNow.Net/Model/DeleteDocumentResponse.cs
> +        public string status { get; set; }
У нас конвеншн: все проперти с большой буквы. Но есть вероятность, что эта модель вообще не нужна.

2019-08-24 10:21 UTC, IvanBil commented on SignNow.Net/Interfaces/IDocumentService.cs
> +        Task<DeleteDocumentResponse> DeleteDocumentAsync(string documentId, CancellationToken cancellationToken = default(CancellationToken));
зачем default(CancellationToken) если можно просто default?

2019-08-24 10:21 UTC, IvanBil commented on SignNow.Net/Interfaces/IDocumentService.cs
> +        /// Deletes a previously uploaded document.
Removes a document from SignNow account

2019-08-24 10:21 UTC, IvanBil commented on SignNow.Net/Interfaces/IDocumentService.cs
> +        /// <param name="documentId">Document ID (string)</param>
Identity of the document to be removed

2019-08-24 14:54 UTC, IvanBil commented on SignNow.Net/Service/DocumentService.cs
> +            var requestedDocument = "/document/" + documentId;
Что если идентификатор документа неправильного формата, например содержит пробелы или запрещенные символы? тогда Uri(ApiBaseUrl, requestedDocument) выдаст непонятный эксепшн. Предлагаю реализовать валидацию айдишника регуляркой и выдавать ошибку с адекватным текстом

2019-08-24 20:56 UTC, AlexNDRmac commented on SignNow.Net/Service/DocumentService.cs
> +            var requestedDocument = "/document/" + documentId;
Да, валидация должна быть для всех внешних параметров. Но, думаю, будет лучше это сделать отдельной задачей.

2019-08-24 21:02 UTC, AlexNDRmac commented on SignNow.Net/Interfaces/IDocumentService.cs
> +        Task<DeleteDocumentResponse> DeleteDocumentAsync(string documentId, CancellationToken cancellationToken = default(CancellationToken));
Привычка после языков с строгой типизаций :)
Упростил...

2019-08-24 21:12 UTC, AlexNDRmac commented on SignNow.Net/Service/DocumentService.cs
> +        public async Task<DeleteDocumentResponse> DeleteDocumentAsync(string documentId, CancellationToken cancellationToken = default(CancellationToken))
Я бы оставил, там возвращается `message`... в случае успешного удаления - все очевидно, но бывают и другие случаи, которые не описаны в документации и это не всегда Exception или Error

2019-08-26 07:03 UTC, IvanBil commented on SignNow.Net/Service/DocumentService.cs
> +        public async Task<DeleteDocumentResponse> DeleteDocumentAsync(string documentId, CancellationToken cancellationToken = default(CancellationToken))
Узнай пожалуйста во вторник у кого-то из апи сайннау есть ли смысл в этом месседже

2019-08-26 08:06 UTC, IvanBil requested changes

2019-08-26 08:06 UTC, IvanBil commented on SignNow.Net.Test/UnitTests/Context/CredentialLoaderTest.cs
> +namespace UnitTests.Context
Just UnitTests

2019-08-30 08:32 UTC, IvanBil requested changes

2019-08-30 08:32 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            using (var request = CreateHttpRequest(requestOptions))
Дублирование кода

2019-08-30 08:32 UTC, IvanBil commented on SignNow.Net/_Internal/Model/ErrorResponse.cs
> +            return message;
What if Errors.Count > 1?

2019-08-30 08:32 UTC, IvanBil commented on SignNow.Net/Service/DocumentService.cs
> +        public async Task<Stream> DeleteDocumentAsync(string documentId, CancellationToken cancellationToken = default)
async Task

2019-08-30 08:32 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +                var apiError = JsonConvert.DeserializeObject<ErrorResponse>(context);
why not use HttpContentToObjectAdapter?

2019-08-30 14:59 UTC, IvanBil approved these changes

2019-08-30 15:00 UTC, merged