Msapi 79
signnow/SignNow.NET pull request #34
Opened 2019-10-24 14:22 UTC by AndriiYudaichev

2019-10-29 14:43 UTC, IvanBil requested changes

2019-10-29 14:43 UTC, IvanBil commented on SignNow.Net/Exceptions/SignNowException.cs
> +    [SuppressMessage("Microsoft.Usage", "CA2237:Mark with SerializableAttribute as Exception implements ISeriazable", Justification = "It is required in case of several AppDomains are used")]
А почему не сделать Serializable?

2019-10-29 14:43 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +        [SuppressMessage("", "CA1822:Method does not access instance data and can be marked as static", Justification = "Method is private and used inside instance method, it will not be used without
почему не сделать статическим? В любом случае этот метод должен быть в другом классе, но пока что оставим его тут

2019-10-29 14:43 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +                var snException = Array.Empty<SignNowException>();
зачем это?

2019-10-29 14:43 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +        [SuppressMessage("", "CA1822:Method does not access instance data and can be marked as static", Justification = "Method is private and used inside instance method, it will not be used without
Почему не сделать статическим?

2019-10-29 14:43 UTC, IvanBil commented on SignNow.Net/OAuth2Service.cs
> +        public async Task<Token> RefreshTokenAsync(Token token, CancellationToken cancellationToken = default)
предлагаю закомментить нереализованные методы

2019-10-29 14:43 UTC, IvanBil commented on SignNow.Net/SignNow.Net.csproj
> +      <NoWarn>1701;1702;1591</NoWarn>
это что?

2019-10-29 15:27 UTC, AndriiYudaichev commented on SignNow.Net/SignNow.Net.csproj
> +      <NoWarn>1701;1702;1591</NoWarn>
1701, 1702 - убрал, их VS по умолчанию подбрасывает, у нас таких ошибок нет
1591 - срабатывает если у публичного метода нет документации (при включенной генерации xml документации), нужно оставить

2019-10-30 13:05 UTC, IvanBil requested changes

2019-10-30 13:05 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +                    throw;
тут не должно выбрасываться эксепшна

2019-10-30 14:21 UTC, IvanBil approved these changes

2019-10-30 14:22 UTC, merged