MSAPI-80 | Initial implementation for Document download
signnow/SignNow.NET pull request #40
Opened 2019-11-11 13:20 UTC by AlexNDRmac

- extended Document service interface
- added Acceptance tests
- refactored Documents test

2019-11-18 15:01 UTC, IvanBil requested changes

2019-11-18 15:01 UTC, IvanBil commented on SignNow.Net/OAuth2Service.cs
> +            return await SignNowClient.RequestAsync<Token>(options, default).ConfigureAwait(false);
раз уж на то пошло, то добавь передачу CancellationToken в метод

2019-11-18 15:01 UTC, IvanBil commented on SignNow.Net/Model/DownloadDocumentResponse.cs
> +        public long? Length { get; set; }
может быть, что длина null?

2019-11-18 15:01 UTC, IvanBil commented on SignNow.Net/Model/DownloadDocumentResponse.cs
> +        public string MediaType { get; set; }
какие значения тут могут быть? может лучше enum?

2019-11-18 15:01 UTC, IvanBil commented on SignNow.Net/_Internal/Helpers/HttpContentAdapter.cs
> +    class HttpContentToResourceAdapter : IHttpContentAdapter<DownloadDocumentResponse>
HttpContentToDownloadDocumentResponseAdapter

2019-11-18 15:01 UTC, IvanBil commented on SignNow.Net/_Internal/Helpers/HttpContentAdapter.cs
> +                Filename = content.Headers.ContentDisposition.FileName.Replace("\"", ""),
content.Headers.ContentDisposition?.FileName?.Replace("\"", ""),

2019-11-18 15:01 UTC, IvanBil commented on SignNow.Net/_Internal/Helpers/HttpContentAdapter.cs
> +                MediaType = content.Headers.ContentType.MediaType,
content.Headers.ContentType?.MediaType

2019-11-18 15:01 UTC, IvanBil commented on SignNow.Net/_Internal/Helpers/HttpContentAdapter.cs
> +        /// <returns><see cref="TObject"/> Models</returns>
Статический анализатор ругается на cref="TObject"

2019-11-18 16:21 UTC, AlexNDRmac commented on SignNow.Net/Model/DownloadDocumentResponse.cs
> +        public long? Length { get; set; }
Да, это по сути состояние из `System.Net.Http.Headers`

2019-11-18 19:43 UTC, AlexNDRmac commented on SignNow.Net/Model/DownloadDocumentResponse.cs
> +        public string MediaType { get; set; }
По идее, должны быть mime types: `application/zip`, `application/pdf`, можно сделать enum

2019-11-19 11:47 UTC, IvanBil commented on SignNow.Net/Model/DownloadDocumentResponse.cs
> +        public long? Length { get; set; }
А что, это норм если сервер вернул контент без указания длины?

2019-11-19 12:06 UTC, AlexNDRmac commented on SignNow.Net/Model/DownloadDocumentResponse.cs
> +        public long? Length { get; set; }
Для случая `no content` - это норм.

2019-11-19 13:28 UTC, IvanBil approved these changes

2019-11-19 13:46 UTC, merged