Feature | Freeform invite
signnow/SignNow.NET pull request #60
Opened 2020-01-02 16:15 UTC by AlexNDRmac

- Added Freeform invite feature to Document service
- Added tests

2020-01-03 12:39 UTC, IvanBil requested changes

2020-01-03 12:39 UTC, IvanBil commented on SignNow.Net/Model/InviteResponse.cs
> +        public string CallbackUrl { get; set; }
тут надо бы прокомментить что это и зачем. Так же непонятно почему это string а не Uri

2020-01-03 12:39 UTC, IvanBil commented on SignNow.Net/Model/FreeFormInvite.cs
> +        public User Sender { get; set; }
разве можно устанавливать сендера?

2020-01-03 12:39 UTC, IvanBil commented on SignNow.Net/Model/FreeFormInvite.cs
> +        public IContent InviteContent()
это нарушение принципа единой ответственности

2020-01-03 12:39 UTC, IvanBil commented on SignNow.Net/Model/FreeFormInvite.cs
> +            return new JsonHttpContent(
эта модель не полная

2020-01-06 11:16 UTC, IvanBil requested changes
see comments. 
You still didn't fix commend in the InviteResponse

2020-01-06 11:16 UTC, IvanBil commented on SignNow.Net/Model/SignInvite.cs
> +        protected SignInvite(string message, string subject)
вместо протектед конструктор должен быть интернал, чтобы нельзя было извне создавать подклассы.
Не нужно этих параметров т.к. они могут принимать нулл. В конструкторе должны быть только параметры, необходимые классу.

2020-01-06 11:16 UTC, IvanBil commented on SignNow.Net/Model/SignInvite.cs
> +        /// <param name="message"></param>
я думаю надо явно в аннотации указать, что сабж и месседж могут оверрайдить стандартные, если не нулл.

2020-01-06 11:16 UTC, IvanBil commented on SignNow.Net/Model/SignInvite.cs
> +        public FreeFormInvite(string to, string message = null, string subject = null) : base(message, subject)
убери опциональные параметры. Они только запутывают. Если to необходим - оставь лишь его

2020-01-06 14:27 UTC, AlexNDRmac commented on SignNow.Net/Model/InviteResponse.cs
> +        public string CallbackUrl { get; set; }
Этот параметр пока не понятен в контексте использования freeform invite
Стринг - потому, что он может быть как `Uri` так и `none`
Уберу его пока, так как он не используется в данный момент

2020-01-09 11:10 UTC, IvanBil approved these changes

2020-01-09 11:48 UTC, merged