Feature | Roles and role-based invite model
signnow/SignNow.NET pull request #65
Opened 2020-01-17 14:01 UTC by AlexNDRmac

- added Roles
- added Role-based invite
- added tests
- suppressed analyzer useless warnings

2020-01-17 15:38 UTC, IvanBil requested changes

2020-01-17 15:38 UTC, IvanBil commented on SignNow.Net/Model/SignNowDocument.cs
> +        /// </summary>
TemplateId

2020-01-17 15:38 UTC, IvanBil commented on SignNow.Net/Model/SignInvite.cs
> +            var originalRole = ExistingDocumentRoles.Find(p => p.Name == role.Name);
а если не найдет?

2020-01-17 15:38 UTC, IvanBil commented on SignNow.Net/Model/SignInvite.cs
> +            RecipientList.Add(content);
нет проверки на повторение ролей

2020-01-17 15:38 UTC, IvanBil commented on SignNow.Net/_Internal/Model/FreeFormInviteRequest.cs
> +    internal class FreeFormInviteRequest
FreeformInvite

2020-01-18 19:45 UTC, AlexNDRmac commented on SignNow.Net/Model/SignInvite.cs
> +            var originalRole = ExistingDocumentRoles.Find(p => p.Name == role.Name);
Добавил SignNowException

2020-01-20 09:02 UTC, IvanBil requested changes

2020-01-20 09:02 UTC, IvanBil commented on SignNow.Net/Model/SignInvite.cs
> +                throw new SignNowException($"Cannot add role to User. Document doesn't have role with name `{role.Name}`");
у нас есть ресурсник со строками. Добавь эту строку в него и согласуй содержимое с Ирой плиз.

2020-01-20 09:40 UTC, IvanBil commented on SignNow.Net/Model/SignNowDocument.cs
> +        /// </summary>
может все-таки назвать это TemplateId?

2020-01-20 10:47 UTC, AlexNDRmac commented on SignNow.Net/Model/SignNowDocument.cs
> +        /// </summary>
Template Id - это другое поле. Я переименую в соответствии с оригинальным названием.

2020-01-20 11:28 UTC, IvanBil approved these changes

2020-01-20 11:28 UTC, merged