Feature | Invite cancel
signnow/SignNow.NET pull request #69
Opened 2020-01-21 13:33 UTC by AlexNDRmac

- Support cancel invite for freeform or role-based
- Added test

2020-01-21 15:25 UTC, IvanBil requested changes

2020-01-21 15:25 UTC, IvanBil commented on SignNow.Net/Interfaces/ISignInvite.cs
> +        Task CancelInviteAsync(SignNowDocument document, CancellationToken cancellationToken = default);
давай может сделаем тут айди документа?

2020-01-21 15:25 UTC, IvanBil commented on SignNow.Net/Service/UserService.cs
> +            if (null == invite)
много кода дублировано

2020-01-21 17:31 UTC, AlexNDRmac commented on SignNow.Net/Interfaces/ISignInvite.cs
> +        Task CancelInviteAsync(SignNowDocument document, CancellationToken cancellationToken = default);
Это подразумевает хранение ID как строки, что не совсем уместно. При желании, можно инстанциировать класс с нужным ID.

2020-01-22 09:19 UTC, IvanBil approved these changes

2020-01-22 09:26 UTC, merged