MSAPI-57 | SignNow client
signnow/SignNow.NET pull request #7
Opened 2019-08-14 08:30 UTC by AlexNDRmac

- basic SignNow Client implementation

2019-08-14 11:57 UTC, IvanBil requested changes

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/SignNowClient.cs
> +                throw new NotImplementedException();
надо выбрасывать кастомный эксепшнт типа SignNowException с указанием сообщения об ошибке из респонса. Сам респонс в чистом виде можно тоже в отдельном свойстве этого эксепшна хранить, кроме того, в любом эксепшне есть дикшнери Data куда можно писать разные подробности (включая заголовки, ответ, итд)

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/SignNowClient.cs
> +            if (method == HttpMethod.Post)
а если Put?

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/SignNowClient.cs
> +        public async Task<TResponse> RequestAsync<TResponse>(RequestOptions requestOptions, CancellationToken cancellationToken)
CancellationToken cancellationToken  = default (CancellationToken)

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/SignNowClient.cs
> +    class SignNowClient : HttpClient, ISignNowClient
в проекте уже есть такой класс в _Internal.Service . Помести этот код в него.
Зачем ты тут наследуешься от HttpClient?

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/SignNowClient.cs
> +        private HttpClient MakeDefaultHttpClient()
мне кажется, что это лишний метод на данном этапе. Но если хочешь, то я бы назвал CreateDefaultHttpClient

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/Model/RequestOptions.cs
> +        public string Method { get; set; }
по-моему есть какой-то стандартный enum для этого. Строка - плохо как по мне

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/Model/RequestOptions.cs
> +        public string Content { get; set; } = string.Empty;
Это должен быть хотя бы object

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/Model/RequestOptions.cs
> +        public Dictionary<string, string> Headers { get; set; }
Думаю ,что это пока лишнее. Будем стараться уйти от назначения кастомных заголовков клиентами.

2019-08-14 11:57 UTC, IvanBil commented on SignNow.Net/Model/RequestOptions.cs
> +        public string Uri { get; set; }
для этого есть тип Uri

2019-08-14 12:20 UTC, AlexNDRmac commented on SignNow.Net/SignNowClient.cs
> +                throw new NotImplementedException();
Это да, в данной задаче я пока ограничился заглушкой. Exceptions можно отдельной задачей завести, чтобы не делать большие pull requests

2019-08-14 12:28 UTC, AlexNDRmac commented on SignNow.Net/SignNowClient.cs
> +    class SignNowClient : HttpClient, ISignNowClient
Да, перенесу. Изначально предполагал, что client будет public...

2019-08-16 11:59 UTC, IvanBil requested changes

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/Model/RequestOptions.cs
> +        public override string HttpMethod => System.Net.Http.HttpMethod.Get.ToString();
using System.Net.Http

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/Model/RequestOptions.cs
> +            Content = content;
я бы не делал контент обязательным. По идее может быть такое, что он не нужен даже в ПОСТ запросе

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/Model/Token.cs
> +        public string GetAccessToken()
сделай это в виде экстеншн метода, чтобы не вносить изменение в данный файл т.к. мерж конфликт с другими ребятами

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            var httpMethod = new HttpMethod(requestOptions.HttpMethod);
так а может сразу хранить HttpMethod в RequestOptions, чтобы не преобразовывать по 2 раза?

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            var requestMessage = new HttpRequestMessage(httpMethod, requestOptions.RequestUrl.ToString());
надо проверку RequestUrl на нул и если так, то выбрасывать ArgumentException с указанием что урл нельзя нул

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            requestMessage.Headers.Add("Authorization", requestOptions.Token.GetAccessToken());
токена может не быть для анонимных запросов. Надо проверку, если есть токен, то добавлять заголовок. Если нет, пропускаем этот шаг

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            requestMessage.Content = this.CreateJsonContent(httpMethod, requestOptions.Content.ToString());
а если это файл? надо проверять является ли контент потоком.
Кроме того если контент нул,  здесь будет исключение

2019-08-16 11:59 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            return JsonConvert.DeserializeObject<TResponse>(contentAsString);
А если TResponse это поток,будет работать?

2019-08-16 12:23 UTC, AlexNDRmac commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            var httpMethod = new HttpMethod(requestOptions.HttpMethod);
Согласен, так будет проще

2019-08-16 14:17 UTC, IvanBil requested changes

2019-08-16 14:17 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +                throw new ArgumentException("Url cannot be empty or null.");
RequestUrl cannot be...

2019-08-16 14:17 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +            requestMessage.Content = this.CreateJsonContent(requestOptions.HttpMethod, contentBody);
почему просто не пропустить этот шаг если нет контента?

2019-08-16 14:17 UTC, IvanBil commented on SignNow.Net/_Internal/Service/SignNowClient.cs
> +                throw new SignNowException(response.ReasonPhrase);
а как же ошибка от сайннау? там же приходит объект с сообщением, который хорошо было бы десериализовать

2019-08-17 18:03 UTC, AlexNDRmac commented on SignNow.Net/Model/Token.cs
> +        public string GetAccessToken()
Пересмотрел коммиты... не вижу проблем с мержами... Extension Method я бы не уносил в класс, который не должен знать внутренней реализации Token. Предлагаю оставить этот Accessor здесь, он позволит нам работать более удобно.

2019-08-21 08:10 UTC, IvanBil approved these changes

2019-08-21 08:11 UTC, merged