Feature | field invite status
signnow/SignNow.NET pull request #76
Opened 2020-02-05 15:34 UTC by AlexNDRmac

- added document status check for field invite
- added faker models
- added tests

2020-02-06 13:29 UTC, IvanBil requested changes

2020-02-06 13:29 UTC, IvanBil commented on SignNow.Net/Model/SignNowDocument.cs
> +                if (IsFreeformInviteSigned() || IsFieldInviteSigned()) return SignStatus.Completed;
what about Cancelled status?

2020-02-06 13:29 UTC, IvanBil commented on SignNow.Net/Model/SignNowDocument.cs
> +                || (FieldInvites.Count > 0 && FieldInvites.Any(i => i.Status == FieldInvitesStatus.Pending));
я думаю ,что все инвайты должны храниться в одной коллекции, как мы и обсуждали ранее. Тогда отпадет необходимость такой сложной проверки

2020-02-06 13:29 UTC, IvanBil commented on SignNow.Net/_Internal/Helpers/Converters/UnixTimeStampJsonConverter.cs
> +            writer.WriteValue($"{ToUnixTimestamp((DateTime)value)}");
ToUnixTimestamp((DateTime)value).ToString()

2020-02-06 13:29 UTC, IvanBil commented on SignNow.Net/_Internal/Model/Field.cs
> +    public class Field
remove public.

2020-02-07 14:10 UTC, IvanBil requested changes

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/Model/SignNowDocument.cs
> +                return new List<SignNowInvite>();
return Array.Empty

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/Model/SignNowDocument.cs
> +                if (InviteStatus.Count > 0 && InviteStatus.All(i => i.Status == SignStatus.Completed || i.Status == SignStatus.Fulfilled))
чем отличаются эти 2 статуса?

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/Model/SignStatus.cs
> +        Fulfilled,
добавь плиз описания к статусам

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/Model/SignNowInvite.cs
> +    public abstract class SignNowInvite
выдели интерфейс для этого класса и его наследников. убери публичные сеттеры

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/Model/SignNowInvite.cs
> +    public sealed class FieldInvite : SignNowInvite
интернал конструктор, чтобы нельзя было создавать вне проекта

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/Model/SignNowInvite.cs
> +    }
это непонятное свойство. Убери из паблика пока

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/_Internal/Model/Field.cs
> +        [JsonProperty("role_id")]
напиши TODO использовать одно свойство типа Role вместо RoleId + RoleName

2020-02-07 14:10 UTC, IvanBil commented on SignNow.Net/Model/SignNowInvite.cs
> +        public virtual SignStatus Status { get; set; }
перенеси аттрибут в FieldInvite

2020-02-07 14:16 UTC, AlexNDRmac commented on SignNow.Net/Model/SignNowDocument.cs
> +                if (InviteStatus.Count > 0 && InviteStatus.All(i => i.Status == SignStatus.Completed || i.Status == SignStatus.Fulfilled))
один статус в freeform, второй в role-based

2020-02-07 15:59 UTC, AlexNDRmac commented on SignNow.Net/Model/SignNowDocument.cs
> +                return new List<SignNowInvite>();
not possible in .Net 4.5, only from 4.6 and newer

2020-02-12 11:41 UTC, IvanBil requested changes

2020-02-12 11:41 UTC, IvanBil commented on SignNow.Net/Model/SignNowDocument.cs
> +        public DocumentStatus Status
это надо кешировать в приватном поле

2020-02-13 09:33 UTC, IvanBil approved these changes

2020-02-13 09:49 UTC, merged