Feature | Field values retrieval
signnow/SignNow.NET pull request #79
Opened 2020-02-23 16:21 UTC by AlexNDRmac

## By creating this pull request, I confirm the following:
* [X] I have read the **[CONTRIBUTING](https://github.com/signnow/SignNow.NET/blob/develop/README.md#contribution-guidelines)** document.
* [ ] My change requires a change to the documentation.
* [X] I have added tests to cover my changes.
* [X] I have updated the documentation accordingly.
* [X] I updated the CHANGELOG.

## Types of changes:

* [X] New feature (non-breaking change which adds functionality)

## Small description of changes:

- Added all SignNow fields models
- Added fields value retrieval for all kind of fields

Thanks

2020-02-24 15:07 UTC, IvanBil requested changes

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/_Internal/Helpers/Converters/StringToUriJsonConverter.cs
> +                Uri.TryCreate(reader.Value.ToString(), UriKind.Absolute, out url);
я думаю, что в таких случаях надо выбрасывать эксепшн о невозможности конвертации

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/_Internal/Helpers/Converters/StringToUriJsonConverter.cs
> +            writer.WriteValue(((Uri)value).OriginalString);
почему не value.ToString() ?

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/Model/Signature.cs
> +namespace SignNow.Net.Model
Move to FieldTypes folder?

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/Model/Signature.cs
> +namespace SignNow.Net.Model
Все типы полей в папке FieldTypes (и неймспейс соответствующий). Почему этот не там?

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/Model/FieldTypes/TextField.cs
> +    public class TextField : BaseField
TextContent
Добавь еще координаты и остальные метаданыне

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/Model/FieldTypes/RadiobuttonField.cs
> +        public int X { get; set; }
может такие общие свойства вынести в базовый класс?

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/Model/FieldTypes/EnumerationField.cs
> +    public class EnumerationField
ToString() ?

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/Model/FieldTypes/AttachmentField.cs
> +        public string Filename { get; set; }
FileName

2020-02-24 15:07 UTC, IvanBil commented on SignNow.Net/Model/FieldTypes/RadiobuttonField.cs
> +        public decimal Width { get; set; }
почему decimal?

2020-02-24 16:17 UTC, AlexNDRmac commented on SignNow.Net/_Internal/Helpers/Converters/StringToUriJsonConverter.cs
> +            writer.WriteValue(((Uri)value).OriginalString);
Потому, что `value.ToString()` - формат не идентичен тому, что был до десериализации.
https://someurl.xyz -> https://someurl.xyz/

2020-02-24 20:31 UTC, AlexNDRmac commented on SignNow.Net/Model/FieldTypes/RadiobuttonField.cs
> +        public decimal Width { get; set; }
Потому что это native data type для этого поля

2020-02-24 20:41 UTC, AlexNDRmac commented on SignNow.Net/Model/FieldTypes/EnumerationField.cs
> +    public class EnumerationField
Не применимо, это всего лишь опции, перегрузка ToString() не имеет смысла для этого объекта

2020-02-24 20:42 UTC, AlexNDRmac commented on SignNow.Net/Model/FieldTypes/RadiobuttonField.cs
> +        public int X { get; set; }
Не все поля имеют эти свойства и не у всех полей эти свойства находятся внутри их структуры как объекта :(

2020-02-26 13:50 UTC, IvanBil requested changes

2020-02-26 13:50 UTC, IvanBil commented on SignNow.Net/Model/FieldContents/EnumerationContent.cs
> +    public class EnumerationContent
почему это не BaseContent?

2020-02-26 13:50 UTC, IvanBil commented on SignNow.Net/Model/FieldContents/RadiobuttonContent.cs
> +    public class RadioContent
почему не наследует  BaseContent?

2020-02-26 13:50 UTC, IvanBil commented on SignNow.Net/Model/Field.cs
> +    public class Field
Inherit interface ISignNowField
Make all properties internal

2020-02-26 13:50 UTC, IvanBil commented on SignNow.Net/Model/FieldContents/BaseContent.cs
> +    public abstract class BaseContent
Нужен интерфейс IDocumentContent с методом object GetValue()

2020-02-26 13:59 UTC, AlexNDRmac commented on SignNow.Net/Model/FieldContents/EnumerationContent.cs
> +    public class EnumerationContent
Потому, что это не контент и общего между ними, только ID

2020-02-26 14:01 UTC, AlexNDRmac commented on SignNow.Net/Model/FieldContents/RadiobuttonContent.cs
> +    public class RadioContent
Та же история, что и с Enumeration

2020-02-28 13:11 UTC, IvanBil requested changes

2020-02-28 13:11 UTC, IvanBil commented on SignNow.Net/Interfaces/ISignNowFieldContent.cs
> +    public interface ISignNowFieldContent
поскольку контент не всегда относится к филду, лучше убрать Field из названия интерфейса и метода

2020-02-28 13:11 UTC, IvanBil commented on SignNow.Net/Interfaces/ISignNowField.cs
> +        string GetFieldContentId();
Зачем этот метод?

2020-02-28 13:11 UTC, IvanBil commented on SignNow.Net/Interfaces/ISignNowField.cs
> +        FieldType FieldType();
Думаю, лучше сделать это свойством

2020-02-28 13:11 UTC, IvanBil commented on SignNow.Net/Model/FieldContents/EnumerationContent.cs
> +    {
почему не унаследовать от ISignNowFieldContent?

2020-02-28 13:11 UTC, IvanBil commented on SignNow.Net/Model/FieldContents/RadiobuttonContent.cs
> +        public List<RadioContent> Radio { get; set; } = new List<RadioContent>();
убери сеттер

2020-02-28 13:11 UTC, IvanBil commented on SignNow.Net/Model/FieldJsonAttributes.cs
> +    public class FieldJsonAttributes
Internal

2020-03-02 13:20 UTC, IvanBil approved these changes

2020-03-02 13:24 UTC, merged